[FragmentStrictMode] Detect Fragment reuse
AndroidX/androidx pull request #142
Opened 2021-03-12 13:48 UTC by simonschiller

## Proposed Changes

  - Detect reuse of `Fragment` instances

## Testing

Test: See `FragmentStrictModeTest#detectFragmentReuse` and `FragmentStrictModeTest#detectFragmentReuseInFlightTransaction`

## Issues Fixed

Fixes: 153738653

2021-03-16 20:12 UTC, jbw0033 requested changes

2021-03-16 20:12 UTC, jbw0033 commented on fragment/fragment/src/main/java/androidx/fragment/app/Fragment.java
> +    boolean mRemovedFromFragmentManager;
This name is long, I think `mRemoved` would be enough.

2021-03-17 20:29 UTC, dlam commented
Build should be passing again now - if you rebase this checks should pass.

2021-03-19 08:05 UTC, simonschiller commented
Rebased and the checks here seem fine, but I got an email notification telling me that they didn't pass. Is this branch green on your internal CI?

2021-03-19 18:29 UTC, dlam commented
I think the lint check has some issues with api files right now on push events - feel free to ignore since checks here are passing.

2021-03-22 23:26 UTC, jbw0033 approved these changes

2021-03-25 02:01 UTC, closed without merging