update KotlinPoet to 1.8.0 for navigation safe-args
AndroidX/androidx pull request #172
Opened 2021-05-02 09:49 UTC by tatocaster

## Proposed Changes

Update KotlinPoet to 1.8.0 for navigation safe-args.

## Testing

Test: ./gradlew test

## Issues Fixed

Fixes: The bug on [https://issuetracker.google.com/issues/183990444](https://issuetracker.google.com/issues/183990444) being fixed

2021-05-02 09:50 UTC, tatocaster commented
except the PR, 

``` kotlin
const val KOTLINPOET = "com.squareup:kotlinpoet:1.4.0"
const val KOTLINPOET_METADATA = "com.squareup:kotlinpoet-metadata:1.4.0"
const val KOTLINPOET_METADATA_SPECS = "com.squareup:kotlinpoet-metadata-specs:1.4.0"
const val KOTLINPOET_CLASSINSPECTOR_ELEMENTS = "com.squareup:kotlinpoet-classinspector-elements:1.4.0"
``` 
Those properties are not used anywhere. I guess we can be safely removed

2021-05-03 04:01 UTC, ianhanniballake requested changes
As part of this, can you please remove the unused dependencies:

> const val KOTLINPOET_METADATA = "com.squareup:kotlinpoet-metadata:1.4.0"
> const val KOTLINPOET_METADATA_SPECS = "com.squareup:kotlinpoet-metadata-specs:1.4.0"
> const val KOTLINPOET_CLASSINSPECTOR_ELEMENTS = "com.squareup:kotlinpoet-classinspector-elements:1.4.0"

2021-05-03 04:01 UTC, ianhanniballake commented on navigation/navigation-safe-args-generator/build.gradle
> +    implementation("com.squareup:kotlinpoet:1.8.0")
Use the `KOTLINPOET` variable here and update the value there.

2021-05-03 17:44 UTC, ianhanniballake approved these changes

2021-05-04 23:51 UTC, closed without merging

2021-05-04 23:52 UTC, ianhanniballake commented
Thanks for the pull request!