Allow exact deep links to contain query parameters
AndroidX/androidx pull request #203
Opened 2021-06-20 09:48 UTC by osipxd

## Proposed Changes

  - Allow exact deep links to contain query parameters
  - Prefer an exact deep link with query parameters over a regular link with query parameters:
  We have two deep links:

myapp://example.io/messages/{userId}?message={messageId}
myapp://example.io/messages/anonymous?message={messageId}
And the link: myapp://example.io/messages/anonymous?message=1

## Testing

Corresponding tests added to NavDestinationAndroidTest
Test: ./gradlew test connectedCheck

## Issues Fixed

Fixes: [185527156](https://issuetracker.google.com/issues/185527156)

2021-06-21 17:15 UTC, sanura-njaka reviewed
Hi Osip, can you please rebase your changes?

2021-06-22 00:21 UTC, sanura-njaka commented on navigation/navigation-common/src/androidTest/java/androidx/navigation/NavDestinationAndroidTest.kt
> +        assertWithMessage("Deep link should extract id argument correctly")
```suggestion
        assertWithMessage("Deep link should extract name argument correctly")
```

2021-06-22 00:27 UTC, sanura-njaka requested changes

2021-06-22 00:27 UTC, sanura-njaka commented on navigation/navigation-common/src/androidTest/java/androidx/navigation/NavDestinationAndroidTest.kt
> +        assertWithMessage("Deep link should extract id argument correctly")
```suggestion
        assertWithMessage("Deep link should extract tab argument correctly")
```

2021-06-22 09:10 UTC, osipxd commented
> Hi Osip, can you please rebase your changes?

Done

2021-06-22 16:06 UTC, sanura-njaka approved these changes

2021-06-22 16:15 UTC, jbw0033 approved these changes

2021-06-22 18:25 UTC, closed without merging