Update Gradle Enterprise plugins
AndroidX/androidx pull request #418
Opened 2022-06-20 09:45 UTC by jprinet

2022-06-21 16:42 UTC, tikurahul approved these changes

2022-06-21 16:43 UTC, tikurahul reviewed
You might need to import these libraries as prebuilts using `development/importMaven`.

2022-06-21 16:44 UTC, tikurahul requested changes
You need to add prebuilts.

2022-06-22 07:11 UTC, jprinet commented
> You might need to import these libraries as prebuilts using `development/importMaven`.

Ok, it's not only the verification-metadata, just read about the prebuilt follow up to your comment.
I don't have time to handle that at the moment.

Let's put this on hold then

2022-06-22 22:41 UTC, closed without merging