Fix upper/lowercase locale issues
AndroidX/androidx pull request #70
Opened 2020-08-21 17:41 UTC by simonschiller

## Proposed Changes

  - Get rid of all `toUpperCase()`, `toLowerCase()`, `capitalize()` and `decapitalize()` calls inside Room without a `Locale` to avoid localization issues (specifically with Turkish).

## Testing

Test: Added one test that verifies this fix (similar to the issue mentioned in the ticket, test fails without my changes)

## Issues Fixed

Fixes: 68159494

2020-08-21 23:32 UTC, dlam commented
@yigit or @danysantiago would either of you mind taking a look?

@simonschiller, first off thanks for submitting this change! One small note - for the `"Fixes: ___"` line, could you update it to just the bug number: 68159494? I.e., `Fixes: 68159494` - this helps with automatically posting update + closing the bug in our issue tracker and I'm not sure it's able to parse the whole URL like that unfortunately.

2020-08-21 23:46 UTC, danysantiago requested changes
Thanks for making this PR - It looking good but you added too many locale changes in projects outside of Room, no biggie, but this change should be scoped on Room. I left a few comments on those other locations so you can revert them.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/dokka/Dokka.kt
> +        val formattedLangauage = language.toLowerCase(Locale.US).capitalize(Locale.US)
Lets revert this file since this is not part of Room.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/Version.kt
> +    fun isAlpha(): Boolean = extra?.toLowerCase(Locale.US)?.startsWith("-alpha") ?: false
Lets revert this file since this is not part of Room.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/StringUtils.kt
> +fun String.capitalize(locale: Locale): String = if (isNotEmpty() && this[0].isLowerCase()) {
This is in the `buildSrc` project, lets revert it since its not in the Room project.

2020-08-21 23:46 UTC, danysantiago commented on sqlite/sqlite/build.gradle
> +    def suffix = StringUtils.capitalize(name, Locale.US)
This is not part of the Room compiler lets revert it.

2020-08-21 23:46 UTC, danysantiago commented on room/runtime/build.gradle
> +    def suffix = StringUtils.capitalize(name, Locale.US)
This is not part of the Room compiler lets revert it.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/jacoco/Jacoco.kt
> +                    "package${v.name.capitalize(Locale.US)}ClassFilesForCoverageReport",
Not part of Room, lets revert this one.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/SourceJarTaskHelper.kt
> +                    project.tasks.named(
This is in the `buildSrc` project lets revert it.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/Release.kt
> +                it.capitalize(Locale.US)
This is in the buildSrc project lets revert it.

2020-08-21 23:46 UTC, danysantiago commented on buildSrc/src/main/kotlin/androidx/build/AndroidXPlugin.kt
> +                "zipResultsOf${task.name.capitalize(Locale.US)}",
This file and a few other are not part of the Room project and are either in another project or part of the `buildSrc` (build infra source) so we should revert those files to scope this change only to Room.

2020-08-22 00:37 UTC, yigit commented
thanks for the PR!
I aggree w/ @danysantiago , lets scope this to Room compiler.

2020-08-22 07:51 UTC, simonschiller commented
Rescoped the changes to the Room compiler only, also fixed the bug link/number.

BTW great job in bringing Jetpack to GitHub, contributing is super simple now. Definitely more PRs incoming 👍

2020-08-24 04:55 UTC, yigit approved these changes
thanks!

2020-08-24 06:30 UTC, yigit commented
the AOSP presubmit failed w/ some ktlint errors.
https://android-review.googlesource.com/c/platform/frameworks/support/+/1407967

Not sure why the github presubmit didn't catch them :/, sorry about that (still working on getting parity between the two).

You can try running:
`:room:room-compiler:ktlint`

Meanwhile, these are the errors from the build server: (sorry, build outputs are not accessible from outside)

```
room/compiler/src/main/kotlin/androidx/room/ext/string_ext.kt:55:8: Unnecessary space(s)

room/compiler/src/main/kotlin/androidx/room/writer/FieldReadWriteWriter.kt:329:1: Exceeded max line length (100) (cannot be auto-corrected)

room/compiler/src/test/kotlin/androidx/room/writer/DaoWriterTest.kt:47:1: Needless blank line(s)
```

Also, super happy to see these PRs, keep them coming! :) We know the process is not great yet so thanks for bearing with us 🙏

2020-08-24 11:43 UTC, simonschiller commented
Fixed it 😄 I guess it's also a good idea to add some docs about Ktlint, see #73

2020-08-24 14:05 UTC, danysantiago approved these changes

2020-08-24 15:14 UTC, closed without merging